config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  #get 'users/new'

  root                   'flips#home'
  get    'signup'     => 'users#new'
  get    'login'      => 'sessions#new'
  post   'login'      => 'sessions#create'
  delete 'logout'     => 'sessions#destroy'
  #Resources
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  before_save { self.username = username.downcase }
  #user validations
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :username, presence: true, length: { maximum: 95 }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/flips_controller.rb
class FlipsController < ApplicationController
  def home
  end

  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      remember user
      redirect_back_or user
    else
      # Create an error message.
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
      redirect_to @user
    else
      render 'edit'
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :username, :password,:password_confirmation)
  end

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      redirect_to login_url
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.       # Documentation comment
  def title(page_title = '')                     # Method def, optional arg
    base_title = " -Flip"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      page_title + base_title               # String concatenation
    end
  end
end

app/helpers/flips_helper.rb
module FlipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end


  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end


  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/flips/home.html.erb
<!DOCTYPE html>
<% provide(:title, "") %>
<html>
<head>

  <!--Title-->
  <title>
    <%= title(yield(:title)) %>
  </title>

</head>


<!--Start of body-->
<body>


<!--Webpage top bar and logo-->
<div class="hero-nav">
    <div class="hero-nav__inner">
      <h1><%= link_to "Flip", root_path , class: "Home"%></h1>
    </div>
</div>
<!--Webpage top bar and logo end-->



<!--Navigation bar-->
<nav class="man">

  <!--School nav bar section-->
  <ul class="dropdown">
    <li class="drop"><a id="school" href="#">School</a>
     <ul class="sub_menu" id="schools">
        <li id="SFU" value="SFU"><a href="#">Simon Fraser University</a></li>
        <li id="UBC" value="UBC"><a href="#">University Of British Columbia</a></li>
     </ul>
    </li>
  </ul>
  <!--School nav bar section end-->

  <!--Faculty nav bar section-->
  <ul class="dropdown">
    <li class="drop"><a id="faculty" href="#">Faculty</a>
      <ul class="sub_menu" id="faculties">
        <li id="ACMA" value="ACMA"><a href="#">ACMA Actuarial Mathematics</a></li>
      </ul>
     </li>
  </ul>
  <!--Faculty nav bar section end-->

  <!--Course nav bar section-->
  <ul class="dropdown">
    <li class="drop"><a id="course" href="#">Course</a>
     <ul class="sub_menu" id="courses">
        <!--<li value=""><a href="#"></a></li>   Populate the list according to the department using javascript/ruby-->
     </ul>
    </li>
  </ul>
  <!--Course nav bar section end-->

</nav>
<!--Navigation bar end-->


<!-- Content-->
<div id="contentBoxApp" ng-app="contentBoxApp">
  <div id="GridCtrl" ng-controller="GridCtrl">
    <div class="container dynamic-grid">
      <article class="grid-item content-box" ng-repeat="(gridKey, gridItem) in gridItems | filter:filterBySearch">
        <div class="inner">
        <img class="content-box-thumb"src="{{ gridItem.img }}" alt="tech image" />
        <h1 class="content-box-header">
          {{ gridItem.headerText }}
        </h1>
        <p class="content-box-blurb">
          {{ gridItem.blurbText }}
        </p>
        <a class="readmore-link" href="#" ng-click="toggleBlurb($event)">read more</a>
        </div>
      </article><!-- /.content-box -->

    </div><!-- /.dynamic-grid -->
  </div><!-- /#GridCtrl -->
</div><!-- /#contentBoxApp -->
<!--Content end -->
<!--  -->


</body>
<!--End of body-->

</html>

app/views/flips/signup.html.erb
<% provide(:title, "Signup") %>
<!--Title-->
<title>
  <%= title(yield(:title)) %>
</title>

<link type="text/css" rel="stylesheet" href="css/sign_in_up.css"/>

<form>
  <input id="input-1" type="text" placeholder="John Doe" required autofocus />
  <label for="input-1">
    <span class="label-text">Full Name</span>
    <span class="nav-dot"></span>
    <div class="signin_up-button-trigger">Sign Up</div>
  </label>
  <input id="input-2" type="email" placeholder="email@address.com" required />
  <label for="input-2">
    <span class="label-text">Email</span>
    <span class="nav-dot"></span>
  </label>
  <input id="input-3" type="text" placeholder="&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;" required />
  <label for="input-3">
    <span class="label-text">Password</span>
    <span class="nav-dot"></span>
  </label>
  <input id="input-4" type="text" placeholder="&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;" required />
  <label for="input-4">
    <span class="label-text">Confirm Password</span>
    <span class="nav-dot"></span>
  </label>
  <button type="submit">Create Your Account</button>
  <p class="tip">Press Tab</p>
  <div class="signin_up-button">Sign Up</div>
</form>

app/views/layouts/_footer.html.erb
<!--Bottom Navigation bar-->
<% if logged_in? %>
<ul class="nav" id="menu">
  <li><%= link_to "Flip", root_path , class: "Home"%></li>
  <li><%= link_to "Post",   '#' %></li>
  <li><%= link_to "Account",   '#' %></li>
  <li><%= link_to "Info",   '#' %></li>
</ul>
<%else%>
<%end%>
<!--Bottom Navigation bar end-->

app/views/layouts/_header.html.erb
<!--sign/sign in/up-->
<% if logged_in? %>
 <div class="wrapperSign">
    <header id="headSign">
      <nav id="navSign">
        <ul>
          <li><%= link_to "profile",  current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        </ul>
      </nav>
    </header>
  </div>
<%else%>
  <div class="wrapperSign">
     <header id="headSign">
       <nav id="navSign">
         <ul>
           <li><%= link_to "Sign in",  login_path %></li>
           <li><%= link_to "Sign up",  signup_path %></li>
         </ul>
       </nav>
     </header>
   </div>
<%end%>
  <!--sign/sign in/up end-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="icon" sizes="16x16 32x32" type="image/x-icon" href="/favicon.ico">
  <title><%= title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit Profile") %>
<!--Title-->
<title>
  <%= title(yield(:title)) %>
</title>


<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.text_field :name, autofocus: true, id: "input-1", placeholder: "Mahmoud Shehata", class: 'form-control'%>
  <label for="input-1">
    <%= f.label :fullname, class: 'label-text' %>
    <span class="nav-dot"></span>
  </label>

  <%= f.email_field :email, id: "input-2", placeholder: "email@address.com", class: 'form-control'%>
  <label for="input-2">
    <%= f.label :email, class: 'label-text' %>
    <span class="nav-dot"></span>
  </label>

  <%= f.text_field :username, id: "input-3", placeholder: "username", class: 'form-control'%>
  <label for="input-3">
    <%= f.label :username, class: 'label-text' %>
    <span class="nav-dot"></span>
  </label>

  <%= f.password_field :password, id: "input-4", placeholder: "Password", required: true, class: 'form-control'%>
  <label for="input-4">
    <%f.label :password, class: 'label-text' %>
    <span class="nav-dot"></span>
  </label>

  <%= f.password_field :password_confirmation, id: "input-5", placeholder: "Password", required: true, class: 'form-control'%>
  <label for="input-5">
    <%= f.label :password_confirmation, "Confirmation", class: 'label-text' %>
    <span class="nav-dot"></span>
  </label>

  <%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<!--Title-->
<title>
  <%= title(yield(:title)) %>
</title>


<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.text_field :name, autofocus: true, id: "input_1", placeholder: "Mahmoud Shehata", required: true, class: 'form-control'%>
  <label for="input_1">
    <%= f.label :fullname, class: 'label-text' %>
    <span class="nav-dot"></span>
  </label>

  <%= f.email_field :email, id: "input_2", placeholder: "email@address.com", required: true, class: 'form-control'%>
  <label for="input_2">
    <%= f.label :email, class: 'label-text' %>
    <span class="nav-dot"></span>
  </label>

  <%= f.text_field :username, id: "input_3", placeholder: "username", required: true, class: 'form-control'%>
  <label for="input_3">
    <%= f.label :username, class: 'label-text' %>
    <span class="nav-dot"></span>
  </label>

  <%= f.password_field :password, id: "input_4", placeholder: "Password", required: true, class: 'form-control'%>
  <label for="input_4">
    <%=f.label :password, class: 'label-text' %>
    <span class="nav-dot"></span>
  </label>

  <%= f.password_field :password_confirmation, id: "input_5", placeholder: "Password", required: true, class: 'form-control'%>
  <label for="input_5">
    <%= f.label :password_confirmation, "Confirmation", class: 'label-text' %>
    <span class="nav-dot"></span>
  </label>

  <%= f.submit "Create my account", class: "btn btn-primary" %>
  <p class="tip">Press Tab</p>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>